apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pods
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: main
      image: ubuntu:20.04
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
